stages:
  - metadata
  - flake-build
  - flake-check
  - noflake-build
  - lint

variables:
  GIT_CLEAN_FLAGS: -ffdx -e gcroots/
  CLICOLOR_FORCE: 1

metadata:
  timeout: 15m
  tags:
    - nix
  stage: metadata
  script:
    - nix flake metadata
    - nix flake show
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

flake-build:
  timeout: 1h
  tags:
    - nix
  stage: flake-build
  script:
    # Keep GC roots
    - mkdir -p gcroots
    - nix build .#qemu-$VARIANT$GUI -o gcroots/qemu-$VARIANT$GUI -L
  parallel:
    matrix:
      - VARIANT: [ espressif, esp32, esp32c3 ]
        GUI: [ "", "-gui" ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

flake-check:
  timeout: 15m
  tags:
    - nix
  stage: flake-check
  script:
    - nix flake check -L
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

noflake-build:
  timeout: 1h
  tags:
    - nix
  stage: noflake-build
  script: |
    mkdir -p gcroots
    NIX_PATH=$NIX_PATH:nixpkgs-overlays=$(pwd)/overlays.nix \
    nix-build \
      https://github.com/NixOS/nixpkgs/archive/$(grep rev flake.lock | sed 's/^.*: //' | sed -e 's/"//g' -e 's/,//').tar.gz \
        --attr qemu-${VARIANT}${GUI} -o gcroots/qemu-$VARIANT$GUI-noflake
    for exe in ./gcroots/qemu-$VARIANT$GUI-noflake/bin/qemu-system-*; do
      echo ${exe}
      ${exe} --version
      ${exe} --machine help
      if [ ${exe} = qemu-system-riscv32 ]; then
        ${exe} --machine help | grep '^esp32c3 ' || (echo ERROR: Did not find expected architecture 'esp32c3'; exit 1)
      elif [ ${exe} = qemu-system-xtensa ]; then
        ${exe} --machine help | grep '^esp32 ' || (echo ERROR: Did not find expected architecture 'esp32'; exit 1)
        ${exe} --machine help | grep '^esp32s3 ' || (echo ERROR: Did not find expected architecture 'esp32s3'; exit 1)
      fi
    done
  parallel:
    matrix:
      - VARIANT: [ espressif, esp32, esp32c3 ]
        GUI: [ "", "-gui" ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

nixfmt:
  timeout: 15m
  tags:
    - nix
  stage: lint
  script:
    - nix fmt -- --version
    - nix fmt -- -vv --tree-root-file flake.nix --ci
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"
