name: "check-qemu-espressif"
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

jobs:
  check-qemu-espressif:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v29
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - run: |
        nix flake check -L
        nix run . -- --version
        nix run .#qemu-esp32 -- --version
        nix run .#qemu-esp32c3 -- --version
        nix fmt
        git diff --exit-code
